export const ArticleAction = {
    remote: {
        FETCH_ARTICLE_BY_SLUG: 'FETCH_ARTICLE_BY_SLUG',
        FETCH_ARTICLES: 'FETCH_ARTICLES',
        FETCH_ARTICLES_BY_SLUG: 'FETCH_ARTICLES_BY_SLUG',
        FETCH_ARTICLES_BY_CATEGORY: 'FETCH_ARTICLES_BY_CATEGORY',
        CREATE_ARTICLE: 'CREATE_ARTICLE',
        UPDATE_ARTICLE: 'UPDATE_ARTICLE',
        DELETE_ARTICLE: 'DELETE_ARTICLE',
    },
    local: {
        FETCH_ARTICLE_SUCCESS: 'FETCH_ARTICLE_SUCCESS',
        FETCH_ARTICLES_SUCCESS: 'FETCH_ARTICLES_SUCCESS',
        FETCH_ARTICLES_BY_SLUG_SUCCESS: 'FETCH_ARTICLES_BY_SLUG_SUCCESS',
        CREATE_ARTICLE_SUCCESS: 'CREATE_ARTICLE_SUCCESS',
        UPDATE_ARTICLE_SUCCESS: 'UPDATE_ARTICLE_SUCCESS',
        DELETE_ARTICLE_SUCCESS: 'DELETE_ARTICLE_SUCCESS',
        ARTICLE_SET_IS_LOADING: 'ARTICLE_SET_IS_LOADING',
    }
};

export const AuthAction = {
    LOGIN: 'LOGIN',
    LOGIN_SUCCESS: 'LOGIN_SUCCESS',
    LOGIN_FAILURE: 'LOGIN_FAILURE',
    LOGOUT: 'LOGOUT',
    REGISTER: 'REGISTER',
    REGISTER_SUCCESS: 'REGISTER_SUCCESS',
    REGISTER_FAILURE: 'REGISTER_FAILURE',
    AUTH_ERROR: 'AUTH_ERROR',
    GET_ALL: 'GET_ALL',
    GET_ALL_SUCCESS: 'GET_ALL_SUCCESS',
    GET_ALL_FAILURE: 'GET_ALL_FAILURE',
    DELETE: 'DELETE',
    DELETE_SUCCESS: 'DELETE_SUCCESS',
    DELETE_FAILURE: 'DELETE_FAILURE',
    CLEAR_REGISTER_SUCCESS: 'CLEAR_REGISTER_SUCCESS'
};

export const UiAction = {
    TOAST_SUCCESS: 'TOAST_SUCCESS',
    TOAST_ERROR: 'TOAST_ERROR',
    TOAST_CLEAR: 'TOAST_CLEAR',
    TOAST_INFO: 'TOAST_INFO',
    TOAST_SHOW: 'TOAST_SHOW',

    // Not implemented yet the below
    MESSAGE_CLEAR_SUCCESS: 'MESSAGE_CLEAR_SUCCESS',
    MESSAGE_CLEAR_ERROR: 'MESSAGE_CLEAR_ERROR',
    MESSAGE_CLEAR_INFO: 'MESSAGE_CLEAR_INFO',
    MESSAGE_CLEAR: 'MESSAGE_CLEAR',
};

export const CategoryAction = {
    remote: {
        FETCH_CATEGORIES: 'FETCH_CATEGORIES',
    },
    local: {
        CATEGORY_SET_IS_LOADING: 'CATEGORY_SET_IS_LOADING',
        FETCH_CATEGORIES_SUCCESS: 'FETCH_CATEGORIES_SUCCESS',
    }
};

export const TagAction = {
    remote: {
        FETCH_TAGS: 'FETCH_TAGS',
    },
    local: {
        TAG_SET_IS_LOADING: 'TAG_SET_IS_LOADING',
        FETCH_TAGS_SUCCESS: 'FETCH_TAGS_SUCCESS',
    }
};

export const CommentAction = {

    remote: {
        CREATE_COMMENT: 'CREATE_COMMENT'
    },
    local: {
        COMMENT_FETCHED_SUCCESS: 'COMMENT_FETCHED_SUCCESS',
        CLEAR_COMMENT_CREATED_FLAG: 'CLEAR_COMMENT_CREATED_FLAG',
        COMMENT_CREATED_SUCCESS: 'COMMENT_CREATED_SUCCESS'
    }
};
